meals_list = [
    {
        "name": "roast",
        "carb": "potato",
        "meat": "chicken",
        "freq": 30,
        "n_meals": 2,
        "cuisine": "",
        "complexity": 2,
    },
    {
        "name": "carbonara",
        "carb": "pasta",
        "meat": "bacon",
        "freq": 30,
        "n_meals": 1,
        "cuisine": "",
        "complexity": 0,
    },
    {
        "name": "chicken rice",
        "carb": "rice",
        "meat": "chicken",
        "freq": 30,
        "n_meals": 2,
        "cuisine": "chinese",
        "complexity": 0,
    },
    {
        "name": "soya chicken",
        "carb": "rice",
        "meat": "chicken",
        "freq": 30,
        "n_meals": 2,
        "cuisine": "chinese",
        "complexity": 0,
    },
    {
        "name": "chilli",
        "carb": "rice",
        "meat": "beef",
        "freq": 30,
        "n_meals": 2,
        "cuisine": "",
        "complexity": 0,
    },
    {
        "name": "pizza",
        "carb": "bread",
        "meat": "various",
        "freq": 30,
        "n_meals": 1,
        "cuisine": "",
        "complexity": 0,
    },
    {
        "name": "grilled salmon",
        "carb": "rice",
        "meat": "fish",
        "freq": 30,
        "n_meals": 1,
        "cuisine": "",
        "complexity": 0,
    },
    {
        "name": "parmigiana",
        "carb": "bread",
        "meat": "none",
        "freq": 30,
        "n_meals": 2,
        "cuisine": "",
        "complexity": 5,
    },
    {
        "name": "toad in the hole",
        "carb": "none",
        "meat": "sausage",
        "freq": 30,
        "n_meals": 2,
        "cuisine": "",
        "complexity": 2,
    },
    {
        "name": "korean pork",
        "carb": "rice",
        "meat": "pork",
        "freq": 30,
        "n_meals": 2,
        "cuisine": "chinese",
        "complexity": 2,
    },
    {
        "name": "lentil curry",
        "carb": "rice",
        "meat": "none",
        "freq": 30,
        "n_meals": 2,
        "cuisine": "",
        "complexity": 0,
    },
    {
        "name": "pork and aubergine",
        "carb": "rice",
        "meat": "pork",
        "freq": 30,
        "n_meals": 2,
        "cuisine": "chinese",
        "complexity": 0,
    },
    {
        "name": "chicken wings",
        "carb": "rice",
        "meat": "chicken",
        "freq": 30,
        "n_meals": 2,
        "cuisine": "chinese",
        "complexity": 0,
    },
    {
        "name": "pasta alla norma",
        "carb": "pasta",
        "meat": "none",
        "freq": 30,
        "n_meals": 1,
        "cuisine": "",
        "complexity": 0,
    },
    {
        "name": "pesto pasta",
        "carb": "pasta",
        "meat": "none",
        "freq": 30,
        "n_meals": 1,
        "cuisine": "",
        "complexity": 0,
    },
    {
        "name": "bolognese",
        "carb": "pasta",
        "meat": "beef",
        "freq": 30,
        "n_meals": 2,
        "cuisine": "",
        "complexity": 3,
    },
    {
        "name": "pasta fagioli",
        "carb": "pasta",
        "meat": "bacon",
        "freq": 30,
        "n_meals": 2,
        "cuisine": "",
        "complexity": 2,
    },
    {
        "name": "baked potato with tuna",
        "carb": "potato",
        "meat": "fish",
        "freq": 30,
        "n_meals": 1,
        "cuisine": "",
        "complexity": 0,
    },
    {
        "name": "pan fried chicken breast",
        "carb": "potato",
        "meat": "chicken",
        "freq": 30,
        "n_meals": 1,
        "cuisine": "",
        "complexity": 0,
    },
    {
        "name": "shakshuka",
        "carb": "bread",
        "meat": "none",
        "freq": 30,
        "n_meals": 1,
        "cuisine": "",
        "complexity": 0,
    },
    {
        "name": "stuffed peppers/tofu",
        "carb": "rice",
        "meat": "pork",
        "freq": 14,
        "n_meals": 2,
        "cuisine": "chinese",
        "complexity": 3,
    },
    {
        "name": "won ton noodle soup",
        "carb": "noodle",
        "meat": "pork",
        "freq": 14,
        "n_meals": 1,
        "cuisine": "chinese",
        "complexity": 3,
    },
    {
        "name": "gyoza",
        "carb": "none",
        "meat": "pork",
        "freq": 14,
        "n_meals": 2,
        "cuisine": "chinese",
        "complexity": 3,
    },
    {
        "name": "stir fry",
        "carb": "rice",
        "meat": "chicken",
        "freq": 14,
        "n_meals": 2,
        "cuisine": "chinese",
        "complexity": 0,
    },
    {
        "name": "char siu",
        "carb": "rice",
        "meat": "pork",
        "freq": 30,
        "n_meals": 2,
        "cuisine": "chinese",
        "complexity": 3,
    },
    {
        "name": "pasta soup",
        "carb": "pasta",
        "meat": "chicken",
        "freq": 14,
        "n_meals": 1,
        "cuisine": "chinese",
        "complexity": 0,
    },
    {
        "name": "black bean belly pork",
        "carb": "rice",
        "meat": "pork",
        "freq": 14,
        "n_meals": 2,
        "cuisine": "chinese",
        "complexity": 0,
    },
    {
        "name": "steamed pork and egg",
        "carb": "rice",
        "meat": "pork",
        "freq": 14,
        "n_meals": 2,
        "cuisine": "chinese",
        "complexity": 0,
    },
    {
        "name": "steamed fish",
        "carb": "rice",
        "meat": "fish",
        "freq": 30,
        "n_meals": 1,
        "cuisine": "chinese",
        "complexity": 2,
    },
    {
        "name": "oyster sauce chicken",
        "carb": "rice",
        "meat": "chicken",
        "freq": 14,
        "n_meals": 2,
        "cuisine": "chinese",
        "complexity": 0,
    },
    {
        "name": "deep fried prawns/peppers",
        "carb": "rice",
        "meat": "prawns",
        "freq": 30,
        "n_meals": 1,
        "cuisine": "chinese",
        "complexity": 2,
    },
    {
        "name": "pork chops",
        "carb": "rice",
        "meat": "pork",
        "freq": 14,
        "n_meals": 2,
        "cuisine": "chinese",
        "complexity": 0,
    },
    {
        "name": "japanese curry",
        "carb": "rice",
        "meat": "chicken",
        "freq": 30,
        "n_meals": 2,
        "cuisine": "chinese",
        "complexity": 0,
    },
      {
        "name": "japanese curry (veggie)",
        "carb": "rice",
        "meat": "none",
        "freq": 30,
        "n_meals": 2,
        "cuisine": "chinese",
        "complexity": 0,
    },
    {
        "name": "chicken and potato",
        "carb": "potato",
        "meat": "chicken",
        "freq": 14,
        "n_meals": 2,
        "cuisine": "chinese",
        "complexity": 0,
    },
    {
        "name": "sausage pasta",
        "carb": "pasta",
        "meat": "sausage",
        "freq": 14,
        "n_meals": 1,
        "cuisine": "",
        "complexity": 0,
    },
    {
        "name": "lasagne",
        "carb": "pasta",
        "meat": "beef",
        "freq": 30,
        "n_meals": 2,
        "cuisine": "",
        "complexity": 5,
    },
    {
        "name": "canneloni ricotta e spinaci",
        "carb": "pasta",
        "meat": "none",
        "freq": 30,
        "n_meals": 1,
        "cuisine": "",
        "complexity": 3,
    },
    {
        "name": "risotto",
        "carb": "rice",
        "meat": "none",
        "freq": 14,
        "n_meals": 1,
        "cuisine": "",
        "complexity": 0,
    },
    {
        "name": "pasta butternut squash",
        "carb": "pasta",
        "meat": "none",
        "freq": 20,
        "n_meals": 1,
        "cuisine": "",
        "complexity": 0,
    },
    {
        "name": "salmon pasta bake",
        "carb": "pasta",
        "meat": "fish",
        "freq": 20,
        "n_meals": 2,
        "cuisine": "",
        "complexity": 2,
    },
    {
        "name": "tuna olive pasta",
        "carb": "pasta",
        "meat": "fish",
        "freq": 20,
        "n_meals": 1,
        "cuisine": "",
        "complexity": 0,
    },
    {
        "name": "cacciatore",
        "carb": "potato",
        "meat": "chicken",
        "freq": 20,
        "n_meals": 2,
        "cuisine": "",
        "complexity": 0,
    },
    {
        "name": "bangers and mash",
        "carb": "potato",
        "meat": "sausages",
        "freq": 20,
        "n_meals": 1,
        "cuisine": "",
        "complexity": 0,
    },
    {
        "name": "veggie lasagna",
        "carb": "pasta",
        "meat": "none",
        "freq": 20,
        "n_meals": 2,
        "cuisine": "",
        "complexity": 0,
    },
    {
        "name": "casserole",
        "carb": "rice",
        "meat": "chicken",
        "freq": 20,
        "n_meals": 2,
        "cuisine": "",
        "complexity": 0,
    },
    {
        "name": "burgers",
        "carb": "bread",
        "meat": "beef",
        "freq": 20,
        "n_meals": 1,
        "cuisine": "",
        "complexity": 2,
    },
    {
        "name": "cottage pie",
        "carb": "potato",
        "meat": "beef",
        "freq": 20,
        "n_meals": 2,
        "cuisine": "",
        "complexity": 2,
    },
    {
        "name": "wraps",
        "carb": "bread",
        "meat": "chicken",
        "freq": 20,
        "n_meals": 1,
        "cuisine": "",
        "complexity": 0,
    },
    {
        "name": "enchilladas",
        "carb": "bread",
        "meat": "chicken",
        "freq": 20,
        "n_meals": 1,
        "cuisine": "",
        "complexity": 0,
    },
]